[package]
name = "fastdl_xz_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "*"
xz2 = "*"
exitcode = "*"
toml = "*"
serde = { version = "*", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true